{% set version = '0.8' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gigrvg
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/GIGrvg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GIGrvg/GIGrvg_{{ version }}.tar.gz
  sha256: 34f3d1accf94278ad37ce3c84d6b11d4e7917552fdc3f79d56c1ecb135b4c026

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ stdlib('c') }}  # [not win]
    - {{ stdlib('m2w64_c') }}  # [win]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('GIGrvg')"           # [not win]
    - "\"%R%\" -e \"library('GIGrvg')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=GIGrvg
  license: GPL-2.0-or-later
  summary: Generator and density function for the Generalized Inverse Gaussian (GIG) distribution.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: GIGrvg
# Type: Package
# Title: Random Variate Generator for the GIG Distribution
# Version: 0.8
# Date: 2023-03-22
# Author: Josef Leydold and Wolfgang Hormann
# Maintainer: Josef Leydold <josef.leydold@wu.ac.at>
# Description: Generator and density function for the Generalized Inverse Gaussian (GIG) distribution.
# License: GPL (>= 2)
# LazyLoad: yes
# NeedsCompilation: yes
# Packaged: 2023-03-21 22:11:17 UTC; leydold
# Repository: CRAN
# Date/Publication: 2023-03-22 14:00:08 UTC
